// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package incominghandler represents the exported interface "wasi:http/incoming-handler@0.2.5".
package incominghandler

import (
	"github.com/a-skua/go-wasi/internal/wasi/http/types"
)

// IncomingRequest represents the exported type alias "wasi:http/incoming-handler@0.2.5#incoming-request".
//
// See [types.IncomingRequest] for more information.
type IncomingRequest = types.IncomingRequest

// ResponseOutparam represents the exported type alias "wasi:http/incoming-handler@0.2.5#response-outparam".
//
// See [types.ResponseOutparam] for more information.
type ResponseOutparam = types.ResponseOutparam
