package example:root;

world http-client {
    include wasi:http/imports@0.2.5;
    include wasi:cli/command@0.2.5;
}

world http-proxy {
    include wasi:cli/imports@0.2.5;
    include wasi:http/proxy@0.2.5;
}

world print {
    include wasi:cli/command@0.2.5;
}
